on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 'lts/*'
          check-latest: true

      - name: Get the latest release ID from samfirm-action
        id: get_latest_release
        run: |
          RESPONSE=$(curl -s https://api.github.com/repos/mazurikian/samfirm.js/releases/latest)
          RELEASE_URL=$(echo $RESPONSE | jq -r .assets[0].browser_download_url)
          echo "RELEASE_URL=$RELEASE_URL" >> $GITHUB_ENV

      - name: Download the latest release
        run: |
          curl -L -o samfirm.tar.gz ${{ env.RELEASE_URL }}

      - name: Extract the downloaded release
        run: |
          tar -xzvf samfirm.tar.gz -C .

      - name: Get the latest firmware version
        id: get_latest_version
        run: |
          REGION="ARO"
          MODEL="SM-A236M"
          IMEI="358263681238947"
          node index.js -r $REGION -m $MODEL -i $IMEI
          FILE_PATH=$(ls $MODEL\_$REGION/*.zip)
          FILE_NAME=$(basename $FILE_PATH)
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV

      - name: Validate FILE_PATH
        run: echo "FILE_PATH=${{ env.FILE_PATH }}"

      - name: Create Release on GitHub
        id: create_release
        run: |
          VERSION="v$(date +'%Y%m%d%H%M%S')"
          RESPONSE=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"tag_name": "'$VERSION'", "name": "'$VERSION'", "body": "Firmware release", "draft": false, "prerelease": false}' \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/releases)
          echo "::set-output name=release_id::$(echo $RESPONSE | jq -r .id)"

      - name: Upload firmware to GitHub Release
        run: |
          RELEASE_ID=${{ steps.create_release.outputs.release_id }}
          FILE_PATH=${{ env.FILE_PATH }}
          FILE_NAME=${{ env.FILE_NAME }}

          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @$FILE_PATH \
            "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=$FILE_NAME"
