on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 'lts/*'
          check-latest: true

      - name: Get the latest release ID from samfirm-action
        id: get_latest_release
        run: |
          RESPONSE=$(curl -s https://api.github.com/repos/mazurikian/samfirm.js/releases/latest)
          echo "Latest release info: $RESPONSE"
          RELEASE_URL=$(echo $RESPONSE | jq -r .assets[0].browser_download_url)
          echo "RELEASE_URL=$RELEASE_URL" >> $GITHUB_ENV

      - name: Download the latest release
        run: |
          curl -L -o samfirm.tar.gz ${{ env.RELEASE_URL }}

      - name: Extract the downloaded release
        run: |
          tar -xzvf samfirm.tar.gz -C .

      - name: Get the latest firmware version
        id: get_latest_version
        run: |
          REGION="ARO" # Puedes modificar la región aquí
          MODEL="SM-A236M" # Modelo del teléfono
          IMEI="358263681238947" # IMEI del teléfono (puedes pasarlo como un input o variable de entorno)
          
          # Ejecuta el script de Node.js con los parámetros adecuados
          node index.js -r $REGION -m $MODEL -i $IMEI
          
          # Después de la ejecución, espera que el archivo esté en la carpeta correspondiente
          # Usamos `ls` para verificar que el archivo está descargado
          ls $MODEL_$REGION/

          # Asignar el nombre del archivo descargado a una variable
          # Cambia esto según el nombre del archivo que se haya generado
          FILE_PATH=$(ls $MODEL_$REGION/*.zip)
          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV

      - name: Upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event_name }}-${{ github.sha }}
          path: ${{ env.FILE_PATH }}
